### PR TITLE
Dev scrapper

### PR DESCRIPTION
**Pull request by Cenorius**
tumblr_ld50v7q6tn1qabw68o1_400

### CODE REVIEW

**Comment by jimen0** [comment]
+1 in recursivity

**Comment by jimen0** [comment]
11/10 recursive

**Comment by Cenorius** [comment]
33689fe1eaf6a3cba950827c626919c1

**Comment by Cenorius** [comment]
6qaybjw

**Comment by Cenorius** [comment]
giphy

**Comment by Cenorius** [comment]
[https://youtu.be/6-HUgzYPm9g](url)

**Pull request merged**
